# -*- coding: utf-8 -*-
"""Aula_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TvX8M5PUAQhS0ZeaWGfAlWOxXUWNLdwO

Váriaveis
"""

def saudacao():
  nome = input('Qual é o seu nome? ')
  print(f'Olá,{nome}')

saudacao()